# Generated by Django 6.0.2 on 2026-02-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='book',
            new_name='book_id',
        ),
    ]
