# Generated by Django 6.0.2 on 2026-02-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_book_order_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='book_id',
            new_name='book',
        ),
    ]
