"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from environs import Env
from datetime import timedelta

env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
	# my apps.
	'books.apps.BooksConfig',
	'accounts.apps.AccountsConfig',

	# default apps.
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django.contrib.sites',

	#third-party apps.
	'rest_framework',
	'rest_framework.authtoken',

	#auth
	'allauth',
	'allauth.account',
	'allauth.socialaccount',
	'allauth.socialaccount.providers.google',

	'dj_rest_auth',
	'dj_rest_auth.registration',
]

MIDDLEWARE = [
	"allauth.account.middleware.AccountMiddleware", # allauth
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': BASE_DIR / 'db.sqlite3',
	}
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Custom settings.
#_______________________________________________________________________________________

# custom user.
AUTH_USER_MODEL = "accounts.CustomUser"

# rest_framework.
REST_FRAMEWORK = {

	'DEFAULT_AUTHENTICATION_CLASSES': [
		'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
		'rest_framework.authentication.SessionAuthentication', # Optional, good for browsable API
	],

	'DEFAULT_PERMISSION_CLASSES': [
		'rest_framework.permissions.AllowAny',
	]
}
REST_AUTH = {
	'USE_JWT': True,
	'JWT_AUTH_COOKIE': 'bookapi-auth',
	'JWT_AUTH_REFRESH_COOKIE': 'bookapi-refresh-token',
	'JWT_AUTH_HTTPONLY': True,
	'JWT_AUTH_SECURE': not DEBUG,
}

# simple jwt.

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# for user uploaded media.
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# for allauth 
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
	
	# Needed to login by username in Django admin, regardless of `allauth`
	'django.contrib.auth.backends.ModelBackend',

	# `allauth` specific authentication methods, such as login by email
	'allauth.account.auth_backends.AuthenticationBackend',
	
]

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['username',"email*", "password1*"]

ACCOUNT_EMAIL_VERIFICATION = 'none' # for email verification
LOGIN_URL = '/api/v1/auth/login/'

SOCIALACCOUNT_PROVIDERS = {
	'google': {
		'APP': {
			'client_id': env('GOOGLE_CLIENT_ID'),
			'secret': env('GOOGLE_CLIENT_SECRET'),
			'key': '' # Leave empty for Google
		},
		'SCOPE': ['profile', 'email'],
		'AUTH_PARAMS': {'access_type': 'online'},
		'OAUTH_PKCE_ENABLED': True,
	}
}
SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"

SOCIALACCOUNT_ADAPTER = "accounts.adapters.CustomSocialAccountAdapter"
